### ISSUE TITLE
Unexpected timezone behaviour for DATE-TIME times

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust-rrule#49]
I have been using rrule in my own project to assist in parsing iCal calendars. Until yesterday I was on 0.5 and was assuming that rrule would leave non-timezone suffixed DATE-TIME well alone. So I was passing in RRULE definitions of the following form:

```
DTSTART:20211214T091500\nEXDATE:20211228T091500,20220104T091500\nRRULE:FREQ=WEEKLY;UNTIL=20220906T091500;INTERVAL=1;BYDAY=TU;WKST=MO
```
And was getting occurrences from rrule that were also in the local time, so no timezone conversion took place. This is what I expected and what I think would be correct.

However with rrule 0.7.1 I now get converted timestamps to UTC like this: `2022-06-07T08:15:00UTC`

This seems incorrect to me.

**Comment by ralpha** [comment]
I know this issue still exists in a few places in the code.
I came across this while updating it. There are still some TODO's present in the code.
Here are a few:
https://github.com/fmeringdal/rust-rrule/blob/main/rrule/src/parser/rrulestr.rs#L663
https://github.com/fmeringdal/rust-rrule/blob/main/rrule/src/parser/rrulestr.rs#L467
https://github.com/fmeringdal/rust-rrule/blob/main/rrule/src/core/properties.rs#L67

But note that simply changing UTC to Local does not fix the problem as it will just move the problem.
This is because the spec defines the timezone to be used depending on `DTSTART` in most cases and that info is not always available or stored correctly at the moment.

So this is a bigger issue and requires a deep dive into the code to fix it. Otherwise we just move the problem and still not follow the spec.

**Comment by aggregat4** [comment]
I can imagine it probably isn't an easy problem to solve but in this particular case we are explicitly in the case of not having a timezone. DTSTART and the other date based fields have floating times not bound to a timezone.

This used to work (probably accidentally then) correctly in 0.5 and I have forked that version and applied a recent other bugfix so I can continue working.

I don't know the codebase of rust-rrule, but would it be an option to at least have floating times work correctly before tackling all other timezones?

**Comment by ralpha** [comment]
> I can imagine it probably isn't an easy problem to solve but in this particular case we are explicitly in the case of not having a timezone. DTSTART and the other date based fields have floating times not bound to a timezone.

It might be a simple fix, I don't know, but the difficult part is making sure everything respects the right rules.

> This used to work (probably accidentally then) correctly in 0.5 and I have forked that version and applied a recent other bugfix so I can continue working.

Since 0.7.0 [a lot has changed](https://github.com/fmeringdal/rust-rrule/blob/main/CHANGELOG.md) in this library. So porting over bug fixes will be more work then fixing the problem itself. There are so many crashes and things that where fixed.

> I don't know the codebase of rust-rrule, but would it be an option to at least have floating times work correctly before tackling all other timezones?

The timezones are just in a few places and codebase is not that difficult.
The lib consists of mainly 2 stages. The parser (`String` -> `RRuleProperties`) and the iterator (`RRuleProperties` to `RRule` and using `into_iter()`).

Checking the first stage is not the difficult. As most of this can be checked easily. There are also enough tests that you can make sure you don't break anything. The 2nd stage is a bit harder because the nature of the code it was ported from. (but problem will most likely be in first stage)

PR's are more then welcome, so if you want, take a look at that first stage. And see if all is still correct there and if needed create fixes. There is also a debug crate in the repo to make this easier.
If you have questions, just ask.
