### ISSUE TITLE
How to parse RRule without start date ?

### ISSUE THREAD

**Issue by EtienneProthon** [fmeringdal/rust-rrule#74]
Since the last version we where able to parse a rrule like `"FREQ=DAILY"` and have it as `RRuleProperties` (on 0.7) or `RRule<Unvalidated>` (on 0.8) now i can't find a way to parse this string. I can only use `RRuleSet::from_str()` that fail when there is no start date

**Comment by fmeringdal** [comment]
Yep, it is true that in `v0.9` we removed the implementation of `Deserialize` and `FromStr` for `RRule`. The reason is that the `until` property on `RRule` can't be made into a `DateTime` without knowing the start date according to the RFC, before `v0.9` we ignored this part of the RFC and had a buggy implementation. 

I already have a workaround in mind for how to potentially solve this and add back `FromStr` impl to `RRule`. But I am curious what your use case is? I assume you don't have the start date and therefore can't use `RRuleSet::from_str`?

**Comment by EtienneProthon** [comment]
Yes this is exactly the point. It's not that i don't have a start date it is that it can change regarding the action the user is expecting. I created an event manager (like google calendar) and when they change some information about an event the user can chose to change only this event, this event and all after or all event. For the two last options i will need to generate new date from different start dates. And what i store in database is only the rrule (with the count, until, freq, weekdays ...), not the start date.

**Comment by fmeringdal** [comment]
I see. May I ask what you use `RRule` for before the iteration? Is it just for validating the structure of the user input or do you have some other use-case?

**Comment by EtienneProthon** [comment]
Yes i validate the user input and apply different date time regarding the action needed (update all after this event or update all). I think i could store the datetime in the rrule and use all_after_with_error with the date of effect. But if i am not wrong DTSTART is not part of the RRULE so in any case having the possibility to parse it separately would be nice.

**Comment by fmeringdal** [comment]
Thank you for the detailed comments. I can see the use-case for it. 
I will be working on adding it back in #78

**Comment by EtienneProthon** [comment]
Perfect ! Thank you very much ! If you need any help feel free to ask !
